/*
 * File: $(model_generator_cxx)/Error.h
 */
#ifndef ERROR_H
#define ERROR_H

#define ERROR_BASE	65535
#define ERROR_MISSING_IED		ERROR_BASE-1
#define ERROR_MISSING_AP		ERROR_BASE-2
#define ERROR_MISSING_LNTYPE	ERROR_BASE-3
#define ERROR_MISSING_DOTYPE	ERROR_BASE-4
#define ERROR_MISSING_DATYPE	ERROR_BASE-5
#define ERROR_LOAD_FILE			ERROR_BASE-6
#define ERROR_PARSE_FILE		ERROR_BASE-7

#endif
