/*
 * File: Error.cpp
 */
#include "Error.h"

char *err_msg[] = {
	"Operation Successfully",
	"Document has no SCL section defined",
	"Document has no DataTypeTemplates section defined",
	"Document has no Communication section defined",
	"Document has more than one SCL section defined",
	"no subnetworks defined",
	"ConnectedAP is missing required attribute 'ied'",
	"ConnectedAP is missing required attribute 'apName'",
	"GSE is missing required attribute 'ldInst'",
	"GSE is missing required attribute 'cbName'",
	"GSE is missing address definition",
	"VLAN-ID value out of range of 0x0FFF",
	"APPID value out of range of 0xFFFF",
	"malformed address",
	"SMV is missing required attribute 'ldInst'",
	"SMV is missing required attribute 'cbName'",
	"SMV is missing address definition",
	"SubNetwork is missing attribute 'name'",
	"AccessPoint as no name definied",
	"AccessPoint has no Server definied",
	"unsupported attribute type",
	"Missing type definition for enumerated data attribute",
	"Wrong type definition for enumerated data attribute",
	"Missing type definition for constructed data attribute",
	"Wrong type definition for constructed data attribute",
	"type declaration missing for data object",
	"DataSet missing required attribute 'name'",
	"GSEControl of type is not supported",
	"no AccessPoint defined in IED",
	"LogControl is missing required attribute 'name'",
	"LogControl is missing required attribute 'logName'",
	"Logical devices misses inst attribute",
	"Logical device misses LN0",
	"required attribute 'lnClass' is missing in logical node",
	"required attribute 'lnType' is missing in logical node",
	"required attribute 'inst' is missing in logical node",
	"missing type declaration",
	"Wrong type for Logical Node",
	"LN other than LN0 is not allowed to contain SettingControl",
	"LN contains more than one SettingControl",
	"Missing data object with name 'doiName'",
	"Missing data attribute with name 'daiName'",
	"Logical node cotains multiple data objects with name 'DONAME'",
	"no lnClass attribute under LogicalNodeType",
	"Missing required attribute 'confRev'",
	"RptEnabled.max!=1 is not allowed when indexed='false'",
	"No logical devices defined for AccessPoint",
	"cdc is missing",
	"DO type definition contains multiple elements of name",
	"DO type definition contains multiple elements of name",
	"DO misses required attribute 'type'",
	"DO misses required attribute 'name'",
	"Enum has no value",
	"Ord attribute missing",
	"id is missing",
	"DAType is missing required attribute 'name'",
	"DAType is missing required attribute 'bType'",
	"Illegal value for boolean attribute",
	"No DataTypeTemplates section found in SCL file",
	"Documents contains more than one SCL section",
	"DA type definition contains multiple elements of name 'BDA'"
};
